
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion'
import p1 from '../assets/images/p7.jpg'

export default function Hero() {
	const x = useSpring(useMotionValue(0), { stiffness: 120, damping: 18 })
	const y = useSpring(useMotionValue(0), { stiffness: 120, damping: 18 })
	const rotateY = useTransform(x, [-150, 150], [-5, 5])
	const rotateX = useTransform(y, [-150, 150], [5, -5])
	const handleMove = (event) => { const rect = event.currentTarget.getBoundingClientRect(); x.set(event.clientX - rect.left - rect.width / 2); y.set(event.clientY - rect.top - rect.height / 2) }
	const resetTilt = () => { x.set(0); y.set(0) }
	return <section id="top" className="grid gap-12 bg-[#FAFAF8] px-6 py-16 lg:grid-cols-2 lg:px-20 lg:py-24"><div className="flex flex-col justify-center"><p data-aos="fade-up" data-aos-delay="100" className="text-xs tracking-[0.3em] text-gray-500">EST. 2024 — DHAKA</p><h1 className="mt-5 font-serif text-6xl leading-[0.9] lg:text-8xl" data-aos="fade-up" data-aos-delay="200" data-aos-duration="1200"><motion.span className="block" initial={{ y: 80, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}>TIME</motion.span><motion.span className="gold-shimmer block" initial={{ y: 80, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.8, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}>WEARS</motion.span><motion.span className="block" initial={{ y: 80, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.8, delay: 0.6, ease: [0.16, 1, 0.3, 1] }}>STYLE</motion.span></h1><p data-aos="fade-up" data-aos-delay="350" className="mt-6 max-w-md text-sm leading-7 text-gray-500">Curated Premium &amp; Luxury Timepieces for the Modern Collector. Authenticity guaranteed.</p><div data-aos="fade-up" data-aos-delay="450" className="mt-8 flex flex-wrap gap-4"><a href="#collection" className="luxury-button rounded-full bg-[#0A0A0A] px-8 py-3 text-sm text-white">Explore Collection</a><a href="#lookbook" className="luxury-button rounded-full border border-black px-8 py-3 text-sm">View Lookbook</a></div></div><motion.div onMouseMove={handleMove} onMouseLeave={resetTilt} style={{ rotateX, rotateY }} data-aos="zoom-in" data-aos-delay="600" data-aos-duration="1400" className="relative flex min-h-[420px] items-center justify-center rounded-2xl border border-black/5 bg-white p-8 shadow-[0_20px_60px_rgba(0,0,0,0.08)]"><img src={p1} alt="Carrera black chronograph" className="hero-watch h-full max-h-[480px] w-full object-contain"/><span className="absolute left-6 top-6 rounded-full bg-white px-4 py-2 text-[10px] tracking-[0.15em] shadow">NEW ARRIVAL — CARRERA EDITION</span><div className="absolute bottom-6 right-6 rounded-xl bg-white p-4 shadow"><p className="text-[10px] uppercase tracking-widest text-gray-400">Starting from</p><p className="font-serif text-xl">৳24,500</p></div></motion.div></section>
}