import { useState } from 'react'
import { motion } from 'framer-motion'

export default function ProductModal({ product, isOpen, onClose, onAddToCart, onRequireDisclaimer }) {
  const [mainImage, setMainImage] = useState(product?.image)
  const [size, setSize] = useState('42mm')
  const [qty, setQty] = useState(1)
  if (!isOpen || !product) return null
  const add = () => product.isHighValue || product.isPreOrder ? onRequireDisclaimer(product, qty) : onAddToCart(product, qty)
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" onClick={onClose}><motion.div initial={{ opacity: 0, scale: .94, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ type: 'spring', stiffness: 300, damping: 30 }} className="grid max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-[1.5rem] bg-white md:grid-cols-2" onClick={(event) => event.stopPropagation()}><div className="p-5 md:p-8"><div className="flex h-[360px] items-center justify-center overflow-hidden rounded-2xl bg-[#FAFAF8] p-8"><img src={mainImage} alt={product.model} className="h-full w-full object-contain transition-transform duration-700 hover:scale-105"/></div><div className="mt-4 flex gap-2">{product.thumbs.map((thumb, index) => <button data-aos="fade-up" data-aos-delay={index * 80} key={thumb} onClick={() => setMainImage(thumb)} className={`h-16 w-16 rounded-xl border-2 p-2 transition-transform ${mainImage === thumb ? 'scale-105 border-black' : 'border-transparent'}`}><img src={thumb} alt="" className="h-full w-full object-contain"/></button>)}</div></div><div className="relative p-8"><button aria-label="Close product details" onClick={onClose} className="absolute right-6 top-5 text-2xl text-gray-400">×</button><p className="text-xs uppercase tracking-[0.2em] text-gray-400">{product.brand}</p><h2 className="mt-2 font-serif text-3xl">{product.model}</h2><p className="mt-4 font-serif text-2xl text-[#D4AF37]">৳{product.price.toLocaleString()}</p><p className="mt-4 text-sm leading-7 text-gray-500">{product.desc}</p><div className="mt-6"><p className="mb-2 text-xs uppercase tracking-widest">Dial Size</p><div className="flex gap-2">{['40mm', '42mm', '44mm'].map((item) => <button key={item} onClick={() => setSize(item)} className={`rounded-full border px-4 py-2 text-xs ${size === item ? 'border-black bg-black text-white' : 'border-black/10'}`}>{item}</button>)}</div></div><div className="mt-5 flex items-center gap-4"><span className="text-xs uppercase tracking-widest">Quantity</span><div className="flex items-center rounded-full border border-black/10"><button onClick={() => setQty(Math.max(1, qty - 1))} className="px-4 py-2">−</button><span className="text-sm">{qty}</span><button onClick={() => setQty(qty + 1)} className="px-4 py-2">+</button></div></div><button onClick={add} className="luxury-button mt-7 w-full rounded-full bg-black py-3 text-sm text-white">Add to Cart — COD</button><a target="_blank" rel="noreferrer" href={`https://wa.me/8801995202915?text=Hi, I want to order ${product.brand} ${product.model} Qty:${qty}`} className="luxury-button mt-3 block w-full rounded-full bg-[#25D366] py-3 text-center text-sm text-white">WhatsApp Order</a></div></motion.div></div>
}